---
- hosts: local
  become: yes
  roles:
    - devops-toolkit
    - ansible-role-awscli
    # - ets-toolkit
  vars:
      ansible_user: "andres"
      hostname: "terminal"
      awscli_users:
        - name: andres
          group: andres
          home: /home/andres
          aws_access_key_id: aaaa
          aws_secret_access_key: bbbb
          s3_configuration:
            - "use_accelerate_endpoint = false"