---
  - name: Check if loans-sre-toolkit is installed
    stat:
      path: "/home/{{ ansible_user }}/loans-sre-toolkit"
    register: gaz_check

  - name: Install GAZ
    git:
      repo: 'git@bitbucket.org:etsprojects/loans-sre-toolkit.git'
      dest: "/home/{{ ansible_user }}/loans-sre-toolkit"
      clone: yes
      depth: 1
    when: not gaz_check.stat.exists
      # ignore_errors: true

  - name: Deploy GAZ p10k
    shell: |
          cd /home/{{ ansible_user }}/loans-sre-toolkit/zsh/plugins/p10k && /bin/zsh deploy.zsh

  - name: Deploy GAZ plugin
    shell: |
          cd /home/{{ ansible_user }}/loans-sre-toolkit/zsh/plugins/gaz && /bin/zsh deploy.zsh

  - name: Copy .p10k.zsh 
    copy:
      src: ../../docker/files/.p10k.zsh
      dest: "/home/{{ ansible_user }}/.p10k.zsh"
      mode: '0755'

  - name: Add Gaz Configuration
    template:
      src:  get-new-token.j2
      dest: "/home/{{ ansible_user }}/.oh-my-zsh/custom/plugins/gaz/get-new-token.js"
      mode: '0755'
    register: source

  # - name: Source the zshrc script
  #   shell: |
  #     /bin/zsh {{ ansible_env.HOME }}/.zshrc

  - name: Source the zshrc script
    shell: |
      source ~/.zshrc
    args: 
      executable: /bin/zsh
      # executable: /bin/bash
    ignore_errors: yes
    when: source
  
  
  - name: Congratulations! you are almost done, :p
    vars:
      msg: |
          < Congrats, {{ ansible_user }}! you can now create a new terminal session! and rerun the playbook just to make sure :p lol!>
            -----------------------
              \
                \
                    .--.
                  |o_o |
                  |:_/ |
                  //   \ \
                (|     | )
                /'\_   _/`\
                \___)=(___/
    debug:
      msg: "{{ msg.split('\n') }}"
           
                
      